modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="cobbledomestics"
version="1.0.0"
displayName="CobbleDomestics"
authors="CuteLess"

[[mixins]]
config = "cobbledomestics.mixins.json"

[[dependencies.cobbledomestics]]
modId="neoforge"
type="required"
versionRange="[21.1.232,)"
ordering="AFTER"
side="BOTH"

[[dependencies.cobbledomestics]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="AFTER"
side="BOTH"

[[dependencies.cobbledomestics]]
modId="cobblemon"
type="required"
versionRange="[1.8.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.cobbledomestics]]
modId="kotlinforforge"
type="required"
versionRange="[5.7.0,)"
ordering="AFTER"
side="BOTH"
